CREATE TABLE SPORT (
	
	SPORTID				NUMERIC NOT NULL PRIMARY KEY,
	SPORTNAME			VARCHAR(50) NOT NULL,
	SPORTMET			NUMERIC,
	SPORTTYPE			CHAR

	);

CREATE TABLE ACTIVITY(

	ACTIVITYID			 NUMERIC NOT NULL PRIMARY KEY,
	ACTIVITYSTARTTIME	 TIME,
	ACTIVITYENDTIME		 TIME,
	ACTIVITYDATE		 DATE,
	ACTIVITYKM			 NUMERIC NOT NULL,
	ACTIVITYCALOR		 NUMERIC,
	ACTIVITYSTARTSITE	 VARCHAR(200),
	ACTIVITYENDSITE		 VARCHAR(200),
	ACTIVITYFKSPORT		 NUMERIC,
	ACTIVITYFKREGISTRY	 NUMERIC,
	ACTIVITYFKTRAINING	 NUMERIC,

	CONSTRAINT FKSPORTID    FOREIGN KEY (ACTIVITYFKSPORT)    REFERENCES SPORT(SPORTID),
	CONSTRAINT FKREGISTRYID FOREIGN KEY (ACTIVITYFKREGISTRY) REFERENCES REGISTRY(REGISTRYID),
	CONSTRAINT FKTRAININGID FOREIGN KEY (ACTIVITYFKTRAINING) REFERENCES TRAINIG(TRAININGID)

);
